DROP DATABASE RF1;

CREATE DATABASE RF1 COLLATE utf8_hungarian_ci;

USE RF1;

DROP TABLE IF EXISTS HIRFOLYAM;
DROP TABLE IF EXISTS MEGALL;
DROP TABLE IF EXISTS MEGALLO;
DROP TABLE IF EXISTS UTAS;
DROP TABLE IF EXISTS BERLET;
DROP TABLE IF EXISTS JEGY;
DROP TABLE IF EXISTS JARAT;

CREATE TABLE JARAT (
  ID INT NOT NULL AUTO_INCREMENT,
  vonalszam VARCHAR(3) NOT NULL,
  tipus VARCHAR(4) NOT NULL,             /*VILL/TROL/BUSZ*/    
  
  PRIMARY KEY(ID)
	
) ENGINE=InnoDB;

CREATE TABLE JEGY (
  azonosito INT NOT NULL AUTO_INCREMENT,
  ar INT NOT NULL,
  tipus VARCHAR(255) NOT NULL,
  ervenyes DATETIME NOT NULL,   /*YYYY-MM-DD HH:MI:SS-ig*/
  ID INT NOT NULL,
  
  PRIMARY KEY(azonosito), 
  
  FOREIGN KEY (ID) 
	REFERENCES JARAT(ID) 
	ON DELETE CASCADE ON UPDATE CASCADE
	
) ENGINE=INNODB;

CREATE TABLE BERLET (
  azonosito INT NOT NULL AUTO_INCREMENT,
  ar INT NOT NULL,
  tipus VARCHAR(255) NOT NULL,
  ervenyes DATETIME NOT NULL,   /*YYYY-MM-DD HH:MI:SS-ig*/
  
  PRIMARY KEY(azonosito)
	
) ENGINE=INNODB;

CREATE TABLE UTAS (
  email VARCHAR(50) NOT NULL,
  jelszo CHAR(82) NOT NULL,
  iranyitoszam INT NOT NULL,
  utca VARCHAR(255) NOT NULL,
  hazszam INT NOT NULL,
  szuletesi_datum DATE NOT NULL,
  vezeteknev VARCHAR(255) NOT NULL,
  keresztnev VARCHAR(255) NOT NULL,
  jegyAzonosito INT NOT NULL,
  berletAzonosito INT NOT NULL,
  adminE bool not null,
  
  PRIMARY KEY(email),
  
  FOREIGN KEY (jegyAzonosito) 
  REFERENCES JEGY(azonosito) 
  ON DELETE CASCADE ON UPDATE CASCADE,

  FOREIGN KEY (berletAzonosito) 
  REFERENCES BERLET(azonosito) 
  ON DELETE CASCADE ON UPDATE CASCADE
  
)ENGINE=INNODB;

CREATE TABLE MEGALLO (
  nev VARCHAR(255) NOT NULL,
  hely VARCHAR(255) NOT NULL,
    
  PRIMARY KEY(nev)
  
) ENGINE=INNODB;

CREATE TABLE MEGALL (
  ID INT NOT NULL,
  nev VARCHAR(255) NOT NULL,
  mikor TIME NOT NULL,
  
  PRIMARY KEY(ID, nev),
  
  FOREIGN KEY (ID) 
	REFERENCES JARAT(ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	
  FOREIGN KEY (nev) 
	REFERENCES MEGALLO(nev) 
	ON DELETE CASCADE ON UPDATE CASCADE
	
) ENGINE=InnoDB;

CREATE TABLE HIRFOLYAM (
  ID INT NOT NULL AUTO_INCREMENT,
  kategória VARCHAR(255) NOT NULL,
  cim VARCHAR(255) NOT NULL,
  leiras LONGTEXT NOT NULL,
  kozzetel_datum DATE NOT NULL,
  
  PRIMARY KEY (ID)

) ENGINE=InnoDB;

